version: '3.8'

services:
  db:
    container_name: 'pos-software-db'
    image: postgres:15.2
    ports:
      - $DB_PORT:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

  sqlx:
    container_name: 'sqlx-migrations'
    build:
      context: .
      dockerfile: docker/sqlx.Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    command: 'tail -F anything'
    depends_on:
      - db    
    volumes:
      - ./migrations:/migrations